### ISSUE TITLE
Some confusion about the data for training the Point-based AutoEncoder

### ISSUE THREAD

**Issue by EAST-J** [Yzmblog/SurfD#2]
Hi, thx for your great work, I am a little confused about the data processing details of the Point-based AutoEncoder training. Did you use all the categories of ShapeNet and Pix3D to train the AE?

**Comment by Yzmblog** [comment]
Hi, thanks for your interest! No, we train it separately for different datasets.

**Comment by FeiiYin** [comment]
Hi, thx for the awesome work! I encountered an issue while testing the image-condition example script on the pix3d dataset. When using the demo image `0049.jpg` (a candlestick) provided in `demo_images/`, the model unexpectedly generates a chair mesh instead of a candlestick. I'm wondering if the model was trained on different categories separately within the pix3d dataset. If not, could you explain why the model produces such cross-category predictions? I followed the example bash script for image-condition exactly as provided.
```
python -m sample.generate_image \
    --model_path pretrained_models/diffusion_image.pt \
    --output_dir ./outputs/image_cond/ \
    --cond_mode img \
    --ae_dir pretrained_models/ae_pix3d.pt \
    --image_path demo_images/0049.jpg \
    --mask_path demo_images/0049.jpg \
    --resolution 512
```
<img width="217" alt="image" src="https://github.com/user-attachments/assets/dc837109-e459-49ef-8c3b-2a6bc8c3b7ef" />
<img width="386" alt="image" src="https://github.com/user-attachments/assets/97ed784d-24fd-4603-9cec-7cf2b1809541" />

**Comment by Yzmblog** [comment]
![image](https://github.com/user-attachments/assets/0386f9c0-275f-4860-b9e6-cc1877e70bc5)
Hi, Thanks for your feedback! There is an error on the command I wrote in readme. I have updated it. The correct result should be like this image. The command should be:
```
python -m sample.generate_image \
    --model_path pretrained_models/diffusion_image.pt \
    --output_dir ./outputs/image_cond/ \
    --cond_mode img \
    --ae_dir pretrained_models/ae_pix3d.pt \
    --image_path demo_images/0049.jpg \
    --mask_path demo_images/0049.png \**(should be png here)**
    --resolution 512
```
Otherwise, it read the image and mask as the same image, so it leads to this error.

And for the model training, we train it on different dataset not different category. In pix3D, we train one model on all the category.

Thanks again! and please let me know if there are still some problems.

**Comment by FeiiYin** [comment]
Yes, it solve my problem! Thanks for your quick response! 👍
